### ISSUE TITLE
Status feedback for expiry rather than dose

### ISSUE THREAD

**Issue by DenisPitcher** [Path-Check/paper-cred#29]
I'm looking at using the paper cred standard but feel the status credential is a bit lacking for my needs and prior to submitting a pull request I thought it'd be useful to discuss it.

In the scenario I'm looking at I want to issue credentials that are suitable for either a recent negative test or a vaccine status.  

Allowing for both provides the greatest flexibility for those not yet able to get the vaccine or those unwilling to do so.

Given the short term acceptability of a recent negative and the uncertainty around how long vaccines would be valid for my thought is that it would be more useful to provide a status with
- expiry date
- FLYY identifier / encrypted PII

That was, at the time of credential issuance it can be determined what the validity period of the status credential is depending on the scenario without exposing any details

**Comment by vitorpamplona** [comment]
Hi Denis! 

Thanks for reaching out! 

Maybe we can create a copy of the Status payload with a different name for this new use case (what would be the best name?). Initially, the [STATUS](https://github.com/Path-Check/paper-cred/blob/main/payloads/status.2.md) payload was thought of as a way to report that vaccine shots have happened (events that happened don't expire) and not that the person is protected or free of covid.

This new payload type should describe exactly what you want to sign. You can add the expiration date if you want to be liable for the COVID-Free decision tree (what happens if you signed that a person is healthy but she/he is not? ) OR you can just report the test result with a test date and the verifier can decide if `x` days from the test date is still COVID-Free or not. 

You can have a simple payload with: 
- Name/Initials/encrypted PII type of field. 
- Expiration date

Or a payload with: 
- Name/Initials/encrypted PII type of field. 
- Last relevant test date
- Last relevant test result
- Last relevant vaccine date
- One or two doses

We support payload types specifically designed for the organization you are working with. Payload type duplication is ok. So you could use a name like NY, which is using "[LibertyPass](https://github.com/Path-Check/paper-cred/blob/main/payloads/liberty.1.md)"

Let me know if this makes sense and your decision.

**Comment by DenisPitcher** [comment]
Thanks, I'll evaluate which direction is best and propose a new payload type for it based upon the feedback I get from our health team
